"""Generate current first-party API declarations; see tools/docs/README.md.

Static declarations are authoritative here. System guides explain runtime
schemas, ownership, nullable returns, units and side effects.
"""
from __future__ import annotations
import argparse
import ast
import os
import re
from pathlib import Path

MARKER = "<!-- Generated by tools/docs/build_reference.py; edit source docs instead. -->"
BT = chr(96)


def lexical_source(source: str, shader=False, mask_strings=False) -> str:
    """Mask comments (and optionally strings), preserving offsets and newlines."""
    out = list(source)
    i = 0
    while i < len(source):
        if source[i] in "'\"":
            delimiter = source[i:i+3] if source[i:i+3] in ("'''", '"""') else source[i]
            end = i + len(delimiter)
            while end < len(source):
                if source[end] == "\\":
                    end += 2
                elif source.startswith(delimiter, end):
                    end += len(delimiter)
                    break
                else:
                    end += 1
            if mask_strings:
                for j in range(i, min(end, len(source))):
                    if out[j] != "\n":
                        out[j] = " "
            i = end
            continue
        is_line = source.startswith("//", i) if shader else source[i] == "#"
        is_block = shader and source.startswith("/*", i)
        if is_line or is_block:
            closing = source.find("*/", i+2) if is_block else source.find("\n", i)
            end = closing + 2 if is_block else closing
            if closing < 0:
                end = len(source)
            for j in range(i, end):
                if out[j] != "\n":
                    out[j] = " "
            i = end
            continue
        i += 1
    return "".join(out)


def _split_top(text, delimiter=","):
    masked, parts, start, depth = lexical_source(text, mask_strings=True), [], 0, 0
    for i, c in enumerate(masked):
        if c in "([{":
            depth += 1
        elif c in ")]}":
            depth -= 1
        elif c == delimiter and depth == 0:
            parts.append(text[start:i].strip())
            start = i+1
    parts.append(text[start:].strip())
    return [p for p in parts if p]


def _compact(text):
    masked, out, space = lexical_source(text, mask_strings=True), [], False
    for i, c in enumerate(text):
        if masked[i] == c and c.isspace():
            if not space:
                out.append(" ")
            space = True
        else:
            out.append(c)
            space = False
    return "".join(out).strip()


def _statement_end(masked, start, terminator=None):
    depth = 0
    for i in range(start, len(masked)):
        c = masked[i]
        if depth == 0 and terminator and c == terminator:
            return i
        if c in "([{":
            depth += 1
        elif c in ")]}":
            depth -= 1
        elif depth == 0 and (c == terminator if terminator else c == "\n"):
            return i
    return len(masked)


def _docs(lines, line):
    i, out = line-2, []
    while i >= 0 and not lines[i].strip():
        i -= 1
    while i >= 0 and lines[i].lstrip().startswith("##"):
        out.append(lines[i].lstrip()[2:].lstrip())
        i -= 1
    return "\n".join(reversed(out)).strip()


def _gd_param(text):
    parts = _split_top(text, "=")
    default = "=".join(parts[1:]).strip() if len(parts) > 1 else None
    match = re.fullmatch(r"(\w+)\s*(?::\s*(.*))?", parts[0])
    if not match:
        raise ValueError("Unsupported parameter: " + text)
    kind = match[2].strip() if match[2] else "not declared"
    if parts[0].endswith(":") and default is not None:
        kind = "inferred from default"
    return {"name": match[1], "type": kind, "default": default}


def _call_params(signature):
    start, depth = signature.index("("), 0
    masked = lexical_source(signature, mask_strings=True)
    for end in range(start, len(masked)):
        if masked[end] == "(":
            depth += 1
        elif masked[end] == ")":
            depth -= 1
            if depth == 0:
                break
    params = [_gd_param(p) for p in _split_top(signature[start+1:end])]
    result = signature[end+1:].strip()
    return params, result[2:].strip() if result.startswith("->") else "not declared"


def parse_gd(source: str) -> dict:
    """Index script and nested-class declarations, excluding method-local fields."""
    clean, masked = lexical_source(source), lexical_source(source, mask_strings=True)
    lines = source.splitlines()
    data = {"docs": "", "extends": "", "class_name": "", "classes": [],
            "functions": [], "properties": [], "signals": [], "enums": []}
    scopes, function_indent, offset, first_decl = [], None, 0, len(lines)
    for index, line in enumerate(masked.splitlines(keepends=True)):
        line_no, start = index+1, offset
        offset += len(line)
        text = line.strip()
        if not text:
            continue
        indent = len(line.expandtabs(4)) - len(line.lstrip().expandtabs(4))
        while scopes and indent <= scopes[-1][0]:
            scopes.pop()
        if function_indent is not None and indent <= function_indent:
            function_indent = None
        scope = ".".join(s[1] for s in scopes)
        def owner(name):
            return scope + "." + name if scope else name
        match = re.match(r"class\s+(\w+)\s*:", text)
        if match:
            data["classes"].append({"name": owner(match[1]), "line": line_no, "docs": _docs(lines, line_no)})
            scopes.append((indent, match[1]))
            continue
        if text.startswith("extends ") and not scopes:
            data["extends"] = clean[start:start+len(line)].strip()[8:]
        if text.startswith("class_name ") and not scopes:
            data["class_name"] = text.split()[1]
        if re.match(r"(?:set\s*\([^)]*\)|get)\s*:", text):
            function_indent = indent
            continue
        match = re.match(r"(?:static\s+)?func\s+(\w+)\s*\(", text)
        if match:
            signature = _compact(clean[start:_statement_end(masked, start, ":")])
            params, result = _call_params(signature)
            data["functions"].append({"name": match[1], "qualified_name": owner(match[1]),
                "signature": signature, "params": params, "return_type": result,
                "line": line_no, "docs": _docs(lines, line_no)})
            function_indent, first_decl = indent, min(first_decl, index)
            continue
        if function_indent is not None:
            continue
        match = re.match(r"signal\s+(\w+)", text)
        if match:
            signature = _compact(clean[start:_statement_end(masked, start)])
            data["signals"].append({"name": match[1], "qualified_name": owner(match[1]),
                "signature": signature, "params": _call_params(signature)[0] if "(" in signature else [],
                "line": line_no, "docs": _docs(lines, line_no)})
            first_decl = min(first_decl, index)
            continue
        match = re.match(r"enum\s+(\w+)?\s*\{", text)
        if match:
            data["enums"].append({"name": owner(match[1] or "(anonymous)"), "line": line_no,
                "signature": _compact(clean[start:_statement_end(masked, start)])})
            first_decl = min(first_decl, index)
            continue
        if re.search(r"\bvar\s+\w+", text):
            declaration = _compact(clean[start:_statement_end(masked, start)])
            declaration = declaration[declaration.index("var ")+4:].rstrip(":").strip()
            item = _gd_param(declaration)
            item.update({"qualified_name": owner(item["name"]), "line": line_no,
                "exported": "@export" in clean[start:start+len(line)] or (index > 0 and lines[index-1].strip().startswith("@export")),
                "docs": _docs(lines, line_no)})
            data["properties"].append(item)
            first_decl = min(first_decl, index)
    for i in range(first_decl):
        if lines[i].lstrip().startswith("##"):
            block = []
            while i < len(lines) and lines[i].lstrip().startswith("##"):
                block.append(lines[i].lstrip()[2:].lstrip())
                i += 1
            data["docs"] = "\n".join(block).strip()
            break
    return data


def parse_python(source: str) -> dict:
    """Use the Python AST to retain real annotations, defaults and method owners."""
    tree = ast.parse(source)
    data = {"docs": ast.get_docstring(tree) or "", "functions": [], "classes": []}
    def visit(nodes, owner=""):
        for node in nodes:
            if isinstance(node, ast.ClassDef):
                name = owner + node.name
                data["classes"].append({"name": name, "line": node.lineno, "docs": ast.get_docstring(node) or ""})
                visit(node.body, name+".")
            elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                args = node.args
                positional = args.posonlyargs + args.args
                defaults = [None]*(len(positional)-len(args.defaults)) + args.defaults
                pairs = list(zip(positional, defaults))
                if args.vararg:
                    pairs.append((args.vararg, None))
                pairs.extend(zip(args.kwonlyargs, args.kw_defaults))
                if args.kwarg:
                    pairs.append((args.kwarg, None))
                params = [{"name": a.arg, "type": ast.unparse(a.annotation) if a.annotation else "not declared",
                    "default": ast.unparse(d) if d is not None else None} for a, d in pairs]
                result = ast.unparse(node.returns) if node.returns else "not declared"
                signature = ("async " if isinstance(node, ast.AsyncFunctionDef) else "") + "def " + node.name + "(" + ast.unparse(args) + ")"
                if node.returns:
                    signature += " -> " + result
                data["functions"].append({"name": node.name, "qualified_name": owner+node.name,
                    "signature": signature, "params": params, "return_type": result, "line": node.lineno,
                    "docs": ast.get_docstring(node) or "", "async": isinstance(node, ast.AsyncFunctionDef)})
                visit(node.body, owner+node.name+".")
            else:
                visit(list(ast.iter_child_nodes(node)), owner)
    visit(tree.body)
    return data


def parse_shader(source: str) -> dict:
    """Index uniforms, helper signatures and assigned Godot stage outputs."""
    clean, masked = lexical_source(source, shader=True), lexical_source(source, shader=True, mask_strings=True)
    kind = re.search(r"\bshader_type\s+(\w+)\s*;", masked)
    modes = re.search(r"\brender_mode\s+([^;]+);", masked)
    data = {"shader_type": kind[1] if kind else "include", "render_modes": modes[1].strip() if modes else "",
            "uniforms": [], "functions": [], "outputs": [],
            "includes": re.findall(r'^\s*#include\s+"([^"]+)"', clean, re.MULTILINE)}
    pattern = r"\b(?:instance\s+|global\s+)?uniform\s+(\w+)\s+(\w+)(\s*\[[^\]]+\])?\s*([^;]*);"
    for match in re.finditer(pattern, masked):
        actual = re.match(pattern, clean[match.start():match.end()])
        tail = actual[4].strip()
        data["uniforms"].append({"name": actual[2], "type": actual[1]+(actual[3] or "").strip(),
            "hint": tail[1:].split("=", 1)[0].strip() if tail.startswith(":") else "",
            "default": tail.split("=", 1)[1].strip() if "=" in tail else None,
            "line": source.count("\n", 0, match.start())+1})
    for match in re.finditer(r"^[ \t]*(\w+)[ \t]+(\w+)[ \t]*\(", masked, re.MULTILINE):
        if match[1] in ("if", "for", "while", "return", "switch"):
            continue
        signature = _compact(clean[match.start():_statement_end(masked, match.start(), "{")])
        if ";" in signature:
            continue
        raw = signature[signature.index("(")+1:signature.rfind(")")]
        params = [{"name": p.split()[-1], "type": " ".join(p.split()[:-1]), "default": None} for p in _split_top(raw)]
        data["functions"].append({"name": match[2], "qualified_name": match[2], "signature": signature,
            "params": params, "return_type": match[1], "line": source.count("\n", 0, match.start())+1, "docs": ""})
    outputs = r"ALBEDO|ALPHA|ALPHA_SCISSOR_THRESHOLD|ROUGHNESS|METALLIC|SPECULAR|EMISSION|NORMAL|NORMAL_MAP|NORMAL_MAP_DEPTH|AO|AO_LIGHT_AFFECT|RIM|RIM_TINT|CLEARCOAT|CLEARCOAT_GLOSS|SSS_STRENGTH|DEPTH|VERTEX|POSITION|UV|UV2|COLOR|FOG|DENSITY|BACKLIGHT|MODELVIEW_MATRIX"
    data["outputs"] = sorted(set(re.findall(r"\b("+outputs+r")(?:\s*\.\s*\w+|\s*\[[^\]\n]+\])*\s*[+\-*/]?=(?!=)", masked)))
    return data


def _code(value, table=False):
    value = str(value).replace("\n", " ")
    if table:
        value = value.replace("|", "\\|")
    runs = re.findall(BT+"+", value)
    delimiter = BT * (max(map(len, runs), default=0)+1)
    padding = " " if value.startswith(BT) or value.endswith(BT) else ""
    return delimiter+padding+value+padding+delimiter


def _link(source, page, line=1):
    return "[Source:"+str(line)+"]("+os.path.relpath(source, page.parent).replace(os.sep, "/")+"#L"+str(line)+")"


def _params(params):
    if not params:
        return ["Parameters: none.", ""]
    rows = ["| Parameter | Type in source | Default |", "| --- | --- | --- |"]
    return rows + ["| "+_code(p["name"], True)+" | "+_code(p["type"], True)+" | "+(_code(p["default"], True) if p["default"] is not None else "required")+" |" for p in params] + [""]


def render_page(source, page, relative, data, language, root):
    guide = os.path.relpath(root/"docs/systems/README.md", page.parent).replace(os.sep, "/")
    rows = [MARKER, "", "# "+relative, "", _link(source, page), "",
        "Declarations come from source. Unannotated types are explicit; see the [system guides]("+guide+") for runtime schemas, nullability, ownership, units and side effects.", ""]
    if data.get("docs"):
        rows += [data["docs"], ""]
    if language == "gdscript":
        rows += ["Base: "+_code(data["extends"] or "not declared")+". Registered class: "+_code(data["class_name"] or "none")+".", ""]
    if language == "shader":
        rows += ["Shader type: "+_code(data["shader_type"])+". Render modes: "+_code(data["render_modes"] or "none declared")+".", ""]
        if data["includes"]:
            rows += ["Includes: "+", ".join(_code(p) for p in data["includes"])+".", ""]
        if data["uniforms"]:
            rows += ["## Uniform inputs", "", "| Name | Type | Default | Hint | Source |", "| --- | --- | --- | --- | --- |"]
            rows += ["| "+_code(u["name"], True)+" | "+_code(u["type"], True)+" | "+(_code(u["default"], True) if u["default"] is not None else "engine default")+" | "+_code(u["hint"] or "none", True)+" | "+_link(source, page, u["line"])+" |" for u in data["uniforms"]]
            rows += [""]
        rows += ["Assigned stage outputs: "+(", ".join(_code(s) for s in data["outputs"]) or "none detected")+".", ""]
    for key, heading in (("classes", "Classes"), ("enums", "Enums")):
        if data.get(key):
            rows += ["## "+heading, ""]
            rows += ["- "+_code(item.get("signature", item["name"]))+" — "+_link(source, page, item["line"]) for item in data[key]]
            rows += [""]
    if data.get("properties"):
        rows += ["## Properties", "", "Long initializers are shortened; follow the source link for their full value.", "",
            "| Property | Type in source | Initializer | Exported | Source |", "| --- | --- | --- | --- | --- |"]
        for p in data["properties"]:
            default = p["default"]
            if default and len(default) > 140:
                default = default[:137]+"..."
            rows += ["| "+_code(p["qualified_name"], True)+" | "+_code(p["type"], True)+" | "+(_code(default, True) if default is not None else "none declared")+" | "+("yes" if p["exported"] else "no")+" | "+_link(source, page, p["line"])+" |"]
        rows += [""]
    for key, heading in (("signals", "Signals"), ("functions", "Functions")):
        if not data.get(key):
            continue
        rows += ["## "+heading, ""]
        for f in data[key]:
            rows += ["### "+f["qualified_name"], "", BT*3+language, f["signature"], BT*3, "", _link(source, page, f["line"]), ""]
            if f.get("docs"):
                rows += [f["docs"], ""]
            rows += _params(f["params"])
            if key == "functions":
                rows += ["Return type: "+_code(f["return_type"])+".", ""]
                if f["name"].startswith("_"):
                    rows += ["Internal helper or engine callback; use system entry points for integration.", ""]
    return "\n".join(rows).rstrip()+"\n"


def source_files(root):
    for folder in ("scripts", "maps", "tools"):
        for path in sorted((root/folder).rglob("*")):
            if path.is_file() and not path.name.startswith("test_") and "__pycache__" not in path.parts and path.suffix in (".gd", ".py", ".gdshader", ".gdshaderinc"):
                yield path
    for path in sorted(root.iterdir()):
        if path.is_file() and path.suffix in (".gd", ".py", ".gdshader", ".gdshaderinc"):
            yield path


def build(root: Path, output: Path, check=False) -> list[Path]:
    """Write references, or list missing/stale/obsolete generated pages without writing."""
    root, output = root.resolve(), output.resolve()
    expected, entries = {}, []
    parsers = {"gdscript": parse_gd, "python": parse_python, "shader": parse_shader}
    counts = dict.fromkeys(("functions", "signals", "properties", "uniforms"), 0)
    for source in source_files(root):
        language = "gdscript" if source.suffix == ".gd" else "python" if source.suffix == ".py" else "shader"
        relative = source.relative_to(root)
        page = output/language/relative.with_suffix(".md")
        data = parsers[language](source.read_text())
        expected[page] = render_page(source, page, relative.as_posix(), data, language, root)
        entries.append((language, relative.as_posix(), page))
        for key in counts:
            counts[key] += len(data.get(key, []))
    rows = [MARKER, "", "# Source API reference", "",
        "Rebuild: "+_code("python3 tools/docs/build_reference.py")+". Check: "+_code("python3 tools/docs/build_reference.py --check")+".", "",
        "Every first-party runtime GDScript, shader and non-test Python tool is listed. Tests, vendor add-ons, imported assets and shell commands belong in developer guides.",
        "", "Types marked "+_code("not declared")+" are unannotated; "+_code("inferred from default")+" preserves GDScript inference syntax. No dynamic object types, schemas, units or nullable returns are guessed.", "",
        "Coverage: "+str(len(entries))+" files; "+", ".join(str(v)+" "+k for k,v in counts.items())+".", ""]
    for language, heading in (("gdscript", "GDScript"), ("shader", "Shaders"), ("python", "Python tools")):
        rows += ["## "+heading, ""] + ["- ["+relative+"]("+page.relative_to(output).as_posix()+")" for kind,relative,page in entries if kind == language] + [""]
    expected[output/"README.md"] = "\n".join(rows).rstrip()+"\n"
    stale = []
    for page, content in expected.items():
        if not page.exists() or page.read_text() != content:
            stale.append(page)
            if not check:
                page.parent.mkdir(parents=True, exist_ok=True)
                page.write_text(content)
    if output.exists():
        for page in output.rglob("*.md"):
            if page not in expected and page.read_text().startswith(MARKER):
                stale.append(page)
                if not check:
                    page.unlink()
    return stale if check else []


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--output", type=Path, help="Defaults to ROOT/docs/reference")
    parser.add_argument("--check", action="store_true", help="Exit 1 for stale pages; write nothing")
    args = parser.parse_args()
    output = args.output or args.root/"docs/reference"
    stale = build(args.root, output, args.check)
    if stale:
        for page in stale:
            print("STALE "+str(page))
        return 1
    print(("Reference is current: " if args.check else "Generated reference: ")+str(output))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
